// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/contact";
  };
  "routes/landing.tsx": {
    id: "routes/landing";
    page: "/";
  };
  "routes/api.contact.ts": {
    id: "routes/api.contact";
    page: "/api/contact";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/landing": typeof import("./app/routes/landing.tsx");
  "routes/api.contact": typeof import("./app/routes/api.contact.ts");
};